spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: passwd
proxy:
  key: proxypool
  limit: 100
  enable-vpn: false
  vpn-host: 127.0.0.1
  vpn-port: 10809
  gather:
    start-page: 1
    interval: 180
  sync:
    period-sync: true
    proxy-sync: true