spring:
  redis:
    host: 127.0.0.1
    port: 6379
proxy:
  key: proxypool
  limit: 200
  enable-vpn: true
  vpn-host: 127.0.0.1
  vpn-port: 10809
  gather:
    start-page: 4
    interval: 180
  sync:
    period-sync: false
    proxy-sync: false